import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { provideTablerIcons, TablerIconComponent } from 'angular-tabler-icons';
import { IconAdjustmentsMinus, IconAdjustmentsPlus, IconAlertHexagon, IconAlertTriangle, IconArrowBackUp, IconArrowsShuffle, IconArticle, IconBell, IconBellRinging, IconBook, IconBox, IconBrandDribbble, IconBrandFacebook, IconBrandGithub, IconBrandInstagram, IconBrandTiktok, IconBrandTwitter, IconBrandWhatsapp, IconBrandX, IconBrandYoutube, IconBriefcase, IconCalculator, IconCalendar, IconCertificate, IconChartPie, IconCheck, IconCheckbox, IconChecklist, IconChevronDown, IconChevronLeft, IconChevronRight, IconChevronUp, IconCircleArrowDown, IconCircleArrowUp, IconCircleFilled, IconCirclePlus, IconClock, IconCornerDownLeftDouble, IconCornerDownRightDouble, IconCreditCard, IconDeviceDesktop, IconDeviceFloppy, IconDeviceLaptop, IconDeviceMobile, IconDevicesQuestion, IconDots, IconDotsVertical, IconDownload, IconEdit, IconExternalLink, IconEye, IconEyeOff, IconFileDescription, IconFileInvoice, IconFileText, IconFilter, IconFilterCancel, IconFlipVertical, IconGavel, IconHeart, IconHeartStar, IconHelpCircle, IconHexagons, IconHome, IconInfoCircle, IconInfoTriangle, IconListSearch, IconLock, IconLogout, IconMail, IconMapPin, IconMenu2, IconMessage2, IconMessageCircle, IconMessageCircleQuestion, IconMinus, IconMoon, IconNote, IconPencil, IconPencilMinus, IconPercentage0, IconPercentage10, IconPercentage100, IconPercentage20, IconPercentage30, IconPercentage40, IconPercentage50, IconPercentage60, IconPercentage70, IconPercentage80, IconPercentage90, IconPhoto, IconPlayerPlay, IconPlus, IconPoint, IconPolaroid, IconPresentationAnalytics, IconReceipt, IconSchema, IconSchool, IconSearch, IconSettings, IconShare, IconSparkles, IconStar, IconStarFilled, IconSun, IconTableDown, IconThumbDown, IconThumbDownFilled, IconThumbUp, IconThumbUpFilled, IconTrash, IconTruckDelivery, IconUser, IconUserCheck, IconUserCircle, IconUsersGroup, IconUserX, IconVideo, IconX, IconZoomIn, IconZoomOut } from "angular-tabler-icons/icons";

const icons = {
  IconX,
  IconInfoCircle,
  IconPencil,
  IconCalculator,
  IconPlus,
  IconHome,
  IconPolaroid,
  IconSettings,
  IconFileDescription,
  IconUserCircle,
  IconUserCheck,
  IconHeart,
  IconPhoto,
  IconDotsVertical,
  IconEye,
  IconExternalLink,
  IconEyeOff,
  IconInfoTriangle,
  IconMinus,
  IconCalendar,
  IconCornerDownLeftDouble,
  IconCornerDownRightDouble,
  IconMenu2,
  IconTrash,
  IconDeviceFloppy,
  IconThumbUp,
  IconThumbUpFilled,
  IconThumbDown,
  IconThumbDownFilled,
  IconStar,
  IconArrowsShuffle,
  IconHelpCircle,
  IconSchema,
  IconFlipVertical,
  IconChevronLeft,
  IconChevronRight,
  IconZoomIn,
  IconZoomOut,
  IconAlertTriangle,
  IconPlayerPlay,
  IconPercentage0,
  IconPercentage10,
  IconPercentage20,
  IconPercentage30,
  IconPercentage40,
  IconPercentage50,
  IconPercentage60,
  IconPercentage70,
  IconPercentage80,
  IconPercentage90,
  IconPercentage100,
  IconUser,
  IconBellRinging,
  IconHeartStar,
  IconMessageCircleQuestion,
  IconStarFilled,
  IconShare,
  IconUserX,
  IconEdit,
  IconCheck,
  IconMoon,
  IconDots,
  IconChevronDown,
  IconCertificate,
  IconLogout,
  IconSun,
  IconSearch,
  IconFilter,
  IconFilterCancel,
  IconAdjustmentsPlus,
  IconAdjustmentsMinus,
  IconMapPin,
  IconUsersGroup,
  IconMessage2,
  IconMessageCircle,
  IconClock,
  IconGavel,
  IconBrandFacebook,
  IconBrandTwitter,
  IconBrandDribbble,
  IconBrandYoutube,
  IconBrandGithub,
  IconBrandInstagram,
  IconBriefcase,
  IconMail,
  IconDeviceDesktop,
  IconFileText,
  IconCircleFilled,
  IconArrowBackUp,
  IconBell,
  IconArticle,
  IconCheckbox,
  IconTruckDelivery,
  IconDownload,
  IconReceipt,
  IconBox,
  IconCirclePlus,
  IconLock,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconCreditCard,
  IconPencilMinus,
  IconSchool,
  IconHexagons,
  IconChartPie,
  IconBook,
  IconNote,
  IconVideo,
  IconChecklist,
  IconDevicesQuestion,
  IconPresentationAnalytics,
  IconFileInvoice,
  IconSparkles,
  IconListSearch,
  IconCircleArrowDown,
  IconPoint,
  IconCircleArrowUp,
  IconBrandWhatsapp,
  IconBrandX,
  IconBrandTiktok,
  IconAlertHexagon,
  IconChevronUp,
};

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    TablerIconComponent
  ],
  exports: [TablerIconComponent],
  providers: [
    provideTablerIcons(icons),
  ],
})
export class IconModule { }


