export const Routes = {
  auth: {
    logins: 'logins',
    new: 'logins/new',
    validate: 'logins/validate-email/:userCode',
    resend: 'logins/resend-code/:userCode',
    refresh: 'logins/refresh',
    logout: 'logins/logout',
  },
  api: {
    users: {
      new_login: 'users/new-login',
      logged: 'users/loged',
      all: 'users',
      contributor: 'users/contributor/:id',
      plan: 'users/plan',
      plan_reset: 'users/plan/reset',
    },
    config: {
      pricing_planes: 'configs/pricing-planes',
      variables: 'variables',
    },
    payments: {
      checkout_session: 'payments/checkout-session',
    },
    genders: {
      all: 'genders',
    },
    roles: {
      all: 'roles',
    },
    learning: {
      categories: 'learning/categories',
      categoriesByCourse: 'learning/categories/course/:courseId',
      sections: 'learning/sections',
      sectionsByCourse: 'learning/sections/course/:courseId',
      topics: {
        base: 'learning/topics',
        by_course: 'learning/topics/course/:courseId',
        syllabus: 'learning/topics/syllabus/:courseId',
        blocks: 'learning/topics/:id/blocks',
        articles: 'learning/topics/:topicId/articles',
      },
      tasks: 'learning/topics/course/:courseId/tasks',
      questions: {
        base: 'learning/questions',
        types: 'learning/questions/types',
        byRule: 'learning/questions/rule/:ruleCode/article/:articleId',
        byArticle: 'learning/questions/article/:articleId',
        navigate: 'learning/questions/article/:articleId/navigate',
      },
      tests: {
        base: 'learning/tests',
        results: 'learning/tests/:testId/course/:courseId/results',
        lastTest: 'learning/tests/last',
        testQuestion: 'learning/tests/questions',
        difficulties: 'learning/tests/difficulties',
        types: 'learning/tests/types',
      },
      difficulties: {
        base: 'learning/difficulties',
      },
      flashcards: {
        base: 'learning/flashcards',
        byRule: 'learning/flashcards/rule/:ruleCode/article/:articleId',
        byArticle: 'learning/flashcards/article/:articleId',
        navigate: 'learning/flashcards/article/:articleId/navigate',
      },
      notes: {
        base: 'learning/notes',
        byRule: 'learning/notes/rule/:ruleCode/article/:articleId',
        navigate: 'learning/notes/article/:articleId/navigate',
      },
      tracker: 'learning/tracker',
      metrics: {
        overview: 'learning/basic-metrics/:courseId/overview',
        topics: 'learning/basic-metrics/:courseId/topics',
        readiness: 'learning/basic-metrics/:courseId/readiness',
        countdown: 'learning/basic-metrics/:courseId/countdown',
        activity: 'learning/basic-metrics/:courseId/activity',
      },
      advancedMetrics: {
        activityTrend: 'learning/advanced-metrics/:courseId/activity-trend',
        topicPerformance: 'learning/advanced-metrics/:courseId/topic-performance',
        weakSpots: 'learning/advanced-metrics/:courseId/weak-spots',
        skillsRadar: 'learning/advanced-metrics/:courseId/skills-radar',
        passProbability: 'learning/advanced-metrics/:courseId/pass-probability',
        studyPlan: 'learning/advanced-metrics/:courseId/study-plan',
      },
      exercises: {
        base: 'learning/courses/exercises',
        by_course: 'learning/courses/exercises/course/:courseId',
        types: 'learning/courses/exercises/types/all',
      },
      courses: {
        base: 'learning/courses',
        my_courses: 'learning/courses/my-courses',
        last_active: 'learning/courses/last-active',
        types: 'learning/courses/types',
        tags: 'learning/courses/tags',
        statuses: 'learning/courses/statuses',
        callingOrgs: 'learning/courses/calling-orgs',
        categories: 'learning/courses/categories',
        topics: 'learning/courses/:id/topics',
        join: 'learning/courses/:id/join',
        is_join: 'learning/courses/:id/is-joined',
        un_join: 'learning/courses/:id/un-join',
        favourite: 'learning/courses/:id/favourite',
        is_favourite: 'learning/courses/:id/is-favourite',
        submitForReview: 'learning/courses/:id/submit-for-review',
        publish: 'learning/courses/:id/publish',
        approve: 'learning/courses/:id/approve',
        reject: 'learning/courses/:id/reject',
        archive: 'learning/courses/:id/archive',
        bulkUpload: {
          template: 'learning/courses/:id/bulk-upload/template',
          validate: 'learning/courses/:id/bulk-upload/validate',
          jobs: 'learning/courses/:id/bulk-upload/jobs',
          job: 'learning/courses/:id/bulk-upload/jobs/:jobId',
        },
        progress: {
          base: 'learning/courses/progress',
          course: 'learning/courses/progress/:courseId',
          topic: 'learning/courses/progress/:courseId/topic/:topicId',
          topic_articles:
            'learning/courses/progress/:courseId/topic/:topicId/articles',
          rule_articles: 'learning/courses/progress/:ruleId/articles',
          article_by_topic:
            'learning/courses/progress/:courseId/topic/:topicId/article/:articleId',
          article_by_rule:
            'learning/courses/progress/:ruleId/article/:articleId',
          article: 'learning/courses/progress/article/:articleId',
        },
      },
      videos: {
        base: 'learning/videos',
        byRule: 'learning/videos/rule/:ruleCode/article/:articleId',
        byArticle: 'learning/videos/article/:articleId',
        navigate: 'learning/videos/article/:articleId/navigate',
      },
      diagrams: {
        base: 'learning/diagrams',
        byRule: 'learning/diagrams/rule/:ruleCode/article/:articleId',
        byArticle: 'learning/diagrams/article/:articleId',
        navigate: 'learning/diagrams/article/:articleId/navigate',
      },
      announcements: {
        base: 'learning/announcements',
        by_course: 'learning/announcements/:courseId',
        views: 'learning/announcements/:id/views',
      },
    },
    seed: {
      categories: 'seed/categories',
      sections: 'seed/sections',
      topics: 'seed/topics',
      questions: 'seed/questions',
      flashcards: 'seed/flashcards',
      videos: 'seed/videos',
      diagrams: 'seed/diagrams',
    },
    rule: {
      base: 'rules',
      article: 'rules/articles/:articleId',
      articles: 'rules/:ruleId/articles',
      index: 'rules/index/:ruleCode',
      types: 'rules/types',
      ambits: 'rules/ambits',
      gazettes: 'rules/gazettes',
      metadata: 'rules/:ruleCode/metadata',
      one_by_id: 'rules/by-id/:id/',
      one_by_code: 'rules/by-code/:ruleCode',
    },
    articles: {
      base: 'articles',
      all_by_rule: 'articles/:ruleId',
    },
    reactions: {
      base: 'reactions',
      feature_vote: 'reactions/feature-vote/',
      vote_state: 'reactions/vote-state',
    },
    reviews: {
      base: 'reviews',
      summary: 'reviews/summary',
      latests: 'reviews/latests',
    },
    comments: {
      base: 'comments',
    },
    ai: {
      base: 'auto-generate',
    },
  },
};
