// SYSTEM VARIABLES
export const SYSTEM_CONFIG = 'SYSTEM_CONFIG';
export const SYSTEM_VARIABLES = 'SYSTEM_VARIABLES';
export const SYS_VAR_MICROSERVICE = 'SYS_VAR_MICROSERVICE';
export const SYS_VAR_DEFAULT_LANGUAGE = 'SYS_VAR_DEFAULT_LANGUAGE';
export const SYS_VAR_LANG_CODES = 'SYS_VAR_LANG_CODES';
export const ROUTES = 'ROUTES';
export const MENU_OPTIONS = 'MENU_OPTIONS';
export const MAX_ENTITY_ITEMS = 'MAX_ENTITY_ITEMS';

// ENTITIES
export const USERS_ENTITY = 'USERS';
export const TENANTS_ENTITY = 'TENANTS';
export const SERVICES_ENTITY = 'SERVICES';
export const BOOKINGS_ENTITY = 'BOOKINGS';
export const ENTITIES = 'ENTITIES';

// BASE ROUTES
export const BASE_ROUTES = 'BASE_ROUTES';
export const API_ROUTES = 'API_ROUTES';
export const AUTH_ROUTES = 'AUTH_ROUTES';
export const ENGI_ROUTES = 'ENGI_ROUTES';

// FRONT ROUTES
export const FRONT_ROUTES = 'FRONT_ROUTES';
export const FRONT_ROUTE_EMPTY = 'FRONT_ROUTE_EMPTY';
export const FRONT_ROUTE_NOTFOUND = 'FRONT_ROUTE_NOTFOUND';
export const FRONT_ROUTE_UNAUTHORIZED = 'FRONT_ROUTE_UNAUTHORIZED';
export const FRONT_ROUTE_AUTH_URL = 'FRONT_ROUTE_AUTH_URL';
export const FRONT_ROUTE_AUTH_RECOVER = 'FRONT_ROUTE_AUTH_RECOVER';
export const FRONT_ROUTE_AUTH_VALIDATE = 'FRONT_ROUTE_AUTH_VALIDATE';

export const FRONT_ROUTE_USER = 'FRONT_ROUTE_USER';
export const FRONT_ROUTE_SUPER = 'FRONT_ROUTE_SUPER';
export const FRONT_ROUTE_CORE = 'FRONT_ROUTE_CORE';

export const FRONT_ROUTE_DEFAULT = 'FRONT_ROUTE_DEFAULT';
export const FRONT_ROUTE_PROFILE = 'FRONT_ROUTE_PROFILE';

export const FRONT_ROUTE_SUPER_UASERS_LIST = 'FRONT_ROUTE_SUPER_UASERS_LIST';
export const FRONT_ROUTE_SUPER_UASERS_CREATE =
  'FRONT_ROUTE_SUPER_UASERS_CREATE';
export const FRONT_ROUTE_SUPER_UASERS_EDIT = 'FRONT_ROUTE_SUPER_UASERS_EDIT';

export const FRONT_ROUTE_SUPER_CLIENTS_LIST = 'FRONT_ROUTE_SUPER_CLIENTS_LIST';
export const FRONT_ROUTE_SUPER_CLIENTS_CREATE =
  'FRONT_ROUTE_SUPER_CLIENTS_CREATE';
export const FRONT_ROUTE_SUPER_CLIENTS_EDIT = 'FRONT_ROUTE_SUPER_CLIENTS_EDIT';

export const FRONT_ROUTE_SUPER_SERVICES_LIST =
  'FRONT_ROUTE_SUPER_SERVICES_LIST';
export const FRONT_ROUTE_SUPER_SERVICES_CREATE =
  'FRONT_ROUTE_SUPER_SERVICES_CREATE';
export const FRONT_ROUTE_SUPER_SERVICES_EDIT =
  'FRONT_ROUTE_SUPER_SERVICES_EDIT';

export const FRONT_ROUTE_CORE_TENANT_LIST = 'FRONT_ROUTE_CORE_TENANT_LIST';
export const FRONT_ROUTE_USER_SHIFTS = 'FRONT_ROUTE_USER_SHIFTS';
export const API_ROUTE_USER_SHIFTS_CREATE = 'API_ROUTE_USER_SHIFTS_CREATE';
export const FRONT_ROUTE_USER_ASSIGNMENTS = 'FRONT_ROUTE_USER_ASSIGNMENTS';

//AUTH ROUTES
export const AUTH_ROUTE_BASE_URL = 'AUTH_ROUTE_BASE_URL';
export const AUTH_ROUTE_LOGIN = 'AUTH_ROUTE_LOGIN';
export const AUTH_ROUTE_LOGIN_RECOVER = 'AUTH_ROUTE_LOGIN_RECOVER';
export const AUTH_ROUTE_SESSION_CREATE = 'AUTH_ROUTE_SESSION_CREATE';
export const AUTH_ROUTE_SESSION_CHECK = 'AUTH_ROUTE_SESSION_CHECK';
export const AUTH_ROUTE_SESSION_VALIDATE = 'AUTH_ROUTE_SESSION_VALIDATE';
export const AUTH_ROUTE_TENANTS = 'AUTH_ROUTE_TENANTS';
export const AUTH_ROUTE_SUPER_CONFIGS = 'AUTH_ROUTE_SUPER_CONFIGS';

//SANUS ROUTES
export const API_ROUTE_BASE_URL = 'API_ROUTE_BASE_URL';
export const API_ROUTE_USER_INFORMATION = 'API_ROUTE_USER_INFORMATION';
export const API_ROUTE_CONFIG = 'API_ROUTE_CONFIG';
export const API_ROUTE_USERS = 'API_ROUTE_USERS';
export const API_ROUTE_WAREHOUSES = 'API_ROUTE_WAREHOUSES';
export const API_ROUTE_USERS_DELETE_MANY = 'API_ROUTE_USERS_DELETE_MANY';
export const API_ROUTE_CLIENTS = 'API_ROUTE_CLIENTS';
export const API_ROUTE_USERS_SHIFTS = 'API_ROUTE_USERS_SHIFTS';
export const API_ROUTE_SUPER_USERS = 'API_ROUTE_SUPER_USERS';
export const API_ROUTE_SUPER_PROCESS_CSV = 'API_ROUTE_SUPER_PROCESS_CSV';
export const API_ROUTE_SUPER_LOAD_CSV = 'API_ROUTE_SUPER_LOAD_CSV';
export const API_ROUTE_CLIENTS_BOOKINGS = 'API_ROUTE_CLIENTS_BOOKINGS';

// ENGI ROUTES
export const ENGI_ROUTE_BASE_URL = 'ENGI_ROUTE_BASE_URL';

// LABELS
export const LABEL_COLUMNS = 'LABEL_COLUMNS';
export const LABEL_GENERATE_URL = 'LABEL_GENERATE_URL';


export const HOURS = [
  '00:00',
  '01:00',
  '02:00',
  '03:00',
  '04:00',
  '05:00',
  '06:00',
  '07:00',
  '08:00',
  '09:00',
  '10:00',
  '11:00',
  '12:00',
  '13:00',
  '14:00',
  '15:00',
  '16:00',
  '17:00',
  '18:00',
  '19:00',
  '20:00',
  '21:00',
  '22:00',
  '23:00',
];
export const QUARTERS = [1, 2, 3, 4];
export const WEEK_DAYS_MONDAY = 'WEEK_DAYS_MONDAY';
export const WEEK_DAYS_TUESDAY = 'WEEK_DAYS_TUESDAY';
export const WEEK_DAYS_WEDNESDAY = 'WEEK_DAYS_WEDNESDAY';
export const WEEK_DAYS_THURSDAY = 'WEEK_DAYS_THURSDAY';
export const WEEK_DAYS_FRIDAY = 'WEEK_DAYS_FRIDAY';
export const WEEK_DAYS_SATURDAY = 'WEEK_DAYS_SATURDAY';
export const WEEK_DAYS_SANDAY = 'WEEK_DAYS_SANDAY';

export const WEEK_DAYS = [
  'WEEK_DAYS_MONDAY',
  'WEEK_DAYS_TUESDAY',
  'WEEK_DAYS_WEDNESDAY',
  'WEEK_DAYS_THURSDAY',
  'WEEK_DAYS_FRIDAY',
  'WEEK_DAYS_SATURDAY',
  'WEEK_DAYS_SANDAY',
];

export const REGISTER_NEW_AVAILABILITY = 'REGISTER_NEW_AVAILABILITY';
export const REGISTER_SHIFT_MULTIPLE = 'REGISTER_SHIFT_MULTIPLE';
export const REGISTER_SHIFT_PERIODICAL = 'REGISTER_SHIFT_PERIODICAL';


//ERRORS
export const ERROR_200 = 'ERROR_200'; // Success
export const ERROR_401 = 'ERROR_401'; // Unautorized
export const ERROR_402 = 'ERROR_402'; // Bad request
export const ERROR_403 = 'ERROR_403'; // Forbidden
export const ERROR_404 = 'ERROR_404'; // Not found
export const ERROR_503 = 'ERROR_503'; // Server error
export const ERROR_500 = 'ERROR_500'; // Server error


// STATUS
export const INFO = 'INFO';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const WARNING = 'WARNING';

// BUTTONS
export const CARERS = 'CARERS';
export const USERS = 'USERS';
export const OVERVIEW = 'OVERVIEW';

export const SPANISH_DATE_FORMATS = {
  parse: {
    dateInput: 'DD/MM/YYYY', // The date format used for parsing user input
  },
  display: {
    dateInput: 'DD/MM/YYYY', // The date format displayed in the input field
    monthYearLabel: 'MMM YYYY', // Format for the month/year label in the calendar header
    dateA11yLabel: 'LL', // Format used for accessibility (optional)
    monthYearA11yLabel: 'MMMM YYYY', // Format used for accessibility (optional)
  },
};